### ISSUE TITLE
Shiny app

### ISSUE THREAD

**Issue by ClementMassonnaud** [PascalCrepey/HospitalNetwork#16]
I uploaded the code for the shiny app

The app can be launched by calling the function `shiny_app()`

This version of the shiny app is from a few weeks ago, I had some troubles integrating it with the package. Maybe there is a better to do it still.
So the modifications / new features committed in the last few weeks might not be implemented in the app for now.

Anyway, I am looking forward to your feedback. Is everything working ok? The features you'd like to see added to the app, remarks about the design, the structure, the workflow, etc.

**Comment by tjibbed** [comment]
Giving it a quick try. Reporting here as I go.

first error I get after installing seems to be a missing dependency: 

> > shiny_app()
> Loading required package: shiny
> 
> Listening on http://127.0.0.1:7735
> Warning: Error in loadNamespace: there is no package called ‘shinyjs’
>   65: <Anonymous>

Installing it helps, the same goes for ‘shinyalert’, which is the next that is missing.

Then, it runs.

**Comment by PascalCrepey** [comment]
Looking at it as well and making it pass the tests / checks without
warning... expect a new commit in a little moment...

**Comment by tjibbed** [comment]
The app looks awesome! I like the way of going through it step by step. It took me a minute to realise that there were other pages than the first checkBase page, but after that it was quite intuitive.
