### ISSUE TITLE
S3 object HospiNet

### ISSUE THREAD

**Issue by PascalCrepey** [PascalCrepey/HospitalNetwork#2]
We need to build an S3 object, let's call it HospiNet, which will contain the hospital matrix and relevant indicators (see vignette for details). This object should have a dedicated summary and print method.

**Comment by PascalCrepey** [comment]
Just created a constructor for this S3 object but no generic method yet...

**Comment by nolwenn** [comment]
Why do you have matrix and edgelist in your object?

**Comment by PascalCrepey** [comment]
Well, sometimes we need the matrix (in spreading simulation) and sometimes we need the edgelist (for igraph), so since both are created at one point I thought we could keep them both and let the user choose what he/she wants...

**Comment by nolwenn** [comment]
But you have methods to go from one to the other, no? You might not want to store the two types in one object as it might take a lot of memory?

**Comment by PascalCrepey** [comment]
mydb = create_fake_patientDB(n_patients = 100000, n_hospital = 2500)
hnet = hospinet_from_patient_database(base = mydb, noloops = FALSE)
format(object.size(hnet), units = "Mb") #27.3Mb
format(object.size(mat$matrix), units = "Mb") #24.3Mb
format(object.size(mat$edgelist), units = "Mb") #3.1Mb

we'll know what to remove if we have a memory size issue... ;-)

**Comment by nolwenn** [comment]
Other question: should not we be able to apply the getMetrics, get_degree... functions on the HospiNet object and not on some igraph object only ?

**Comment by PascalCrepey** [comment]
Sure but that would mean either
- having an igraph object within HospiNet (which raises the question you
asked before about size efficiency
- or doing the igraph converting at the getMetrics level  (I think it's
what I introduced in one of my last commits)
- switch HospiNet from S3 to R6 and have an active field which would create
the igraph on the fly if and when it's needed (maybe the best solution...)



Le jeu. 1 août 2019 à 13:30, Nolwenn Le Meur <notifications@github.com> a
écrit :

**Comment by tjibbed** [comment]
I will need to do some reading up here on the difference between S3 and R6 objects, but the last option sounds like the best solution to me, indeed. 

As for @nolwenn 's question, it seems most intuitive to be able to apply these functions on the HospiNet object.

**Comment by PascalCrepey** [comment]
I've implemented the R6 mechanism. You can see it at work at the end of the work-flow vignette (text of the vignette still needs to be updated...)

**Comment by tjibbed** [comment]
Brilliant. Hadn't noticed yet... I'm still catching/reading up after being away for a week and a half.
