### ISSUE TITLE
Fake data

### ISSUE THREAD

**Issue by PascalCrepey** [PascalCrepey/HospitalNetwork#3]
We need a fake dataset corresponding to the description given in the vignette. Our functions will be tested against this fake dataset to ensure their compliance.

**Comment by tjibbed** [comment]
Sure, do we need to introduce some errors in the fake data as well? Just to see that the data management functions work accordingly and pick it up?

Let me see if I create something.

**Comment by PascalCrepey** [comment]
Just created a fake dataset generator so that we can try different number of patients and hospitals as well as test the windows. I guess you may write a function introducing specific errors so that we can test the diagnostic functions...

**Comment by PascalCrepey** [comment]
I've updated the fake data functions so that we now also have a function generating a clustered network.

**Comment by tjibbed** [comment]
Will see if I can write a function to introduce errors into the fake data.
