### ISSUE TITLE
Error when column name equals variable name

### ISSUE THREAD

**Issue by tjibbed** [PascalCrepey/HospitalNetwork#7]
If I call the column containing the patient identifier "patientID", I get the following error message:

> Error in checkFormat(new_base, patientID = patientID, hospitalID = hospitalID,  : 
>   The following column(s) is/are missing: pID. Please check that your database contains at least the columns mentionned in the documentation, and that they are in the right format. Names are case sensitive.

With any other column name, the script runs just fine.

The same happens for the other three required variables. e.g. if hospitalID="hospitalID". For some reason, R gets confused if the variable name is the same as the column name.

I think there are two general solutions to the problem:
1) The proper route: try and find out how this referencing of names produces this error and see if there is a better way of dealing with this (e.g. using ..patientID [Tried this, but didn't solve all of the problems])
2) Hard-wire a check to see if variable names and column names are the same, and rename them if so.

**Comment by tjibbed** [comment]
I found out it's not exactly the same error that happens for the other variables.

for hospitalID, I get:
>  Error in get(hospitalID) : object '18091301' not found  
where 18091301 is a hospital code

for admDate:
>  Error: invalid first argument 

with traceBack:
> 10. stop(err$message, call. = FALSE) 
> 9. .checkTypos(e, names(x)) 
> 8. value[[3L]](cond) 
> 7. tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
> 6. tryCatchList(expr, classes, parentenv, handlers) 
> 5. tryCatch(eval(.massagei(isub), x, parent.frame()), error = function(e) .checkTypos(e, 
>     names(x))) 
> 4. `[.data.table`(base, get(admDate) > get(disDate), , which = T) at DataManagement.R#302
> 3. base[get(admDate) > get(disDate), , which = T] at DataManagement.R#302
> 2. checkDates(base = checkResults$base, patientID = patientID, hospitalID = hospitalID, 
>     admDate = admDate, disDate = disDate, convertDates = convertDates, 
>     dateFormat = dateFormat, deleteErrors = deleteErrors, verbose = verbose, 
>     ...) at DataManagement.R#62
> 1. checkBase(countryData, deleteMissing = "patient", deleteErrors = "patient", 
>     convertDates = TRUE, dateFormat = "%y%m%d", patientID = "pID", 
>     hospitalID = "hID", disDate = "dis", admDate = "admDate", 
>     verbose = TRUE, maxIteration = 250) 

and for disDate the same with traceBack:

> 10. stop(err$message, call. = FALSE) 
> 9. checkTypos(e, names(x)) 
> 8. value[[3L]](cond) 
> 7. tryCatchOne(expr, names, parentenv, handlers[[1L]]) 
> 6. tryCatchList(expr, classes, parentenv, handlers) 
> 5. tryCatch(eval(.massagei(isub), x, parent.frame()), error = function(e) .checkTypos(e, 
>     names(x))) 
> 4. `[.data.table`(base, get(admDate) > get(disDate), , which = T) at DataManagement.R#302
> 3. base[get(admDate) > get(disDate), , which = T] at DataManagement.R#302
> 2. checkDates(base = checkResults$base, patientID = patientID, hospitalID = hospitalID, 
>     admDate = admDate, disDate = disDate, convertDates = convertDates, 
>     dateFormat = dateFormat, deleteErrors = deleteErrors, verbose = verbose, 
>     ...) at DataManagement.R#62
> 1. checkBase(countryData, deleteMissing = "patient", deleteErrors = "patient", 
>     convertDates = TRUE, dateFormat = "%y%m%d", patientID = "pID", 
>     hospitalID = "hID", disDate = "disDate", admDate = "adm", 
>     verbose = TRUE, maxIteration = 250)

**Comment by PascalCrepey** [comment]
Hi Tjibbe, 
now : 
```
mydb = create_fake_patientDB(n_patients = 100, n_hospital = 5)
mat1 = hospinet_from_patient_database(base = mydb)
```
and

```
setnames(mydb, 1:2, c("patientID", "hospitalID"))
mat2 = hospinet_from_patient_database(base = mydb, patientID = "patientID", hospitalID = "hospitalID")
```

give the same thing.

The problem was that the resolution of the variables in R is done in multiple context, first the current, and if nothing is found, the parent, etc... Hence the issue can be simplified as: 

```
dt = data.table(a = 1:5)
a = "a"
var = "a"

dt[, get(var)] #works as intended
dt[, get(a)] #fails 
```
One option to solve this would be to force resolution in the parent environment by deactivating the resolution within the data.table: 
```
dt[, get(var), with = FALSE]
dt[, get(a), with = FALSE]
```
or use the shorter version ".." which disable nothing but indicate that the variable needs to be looked in the parent environment (hence not in the data.table)
```
dt[, ..var]
dt[, ..a]
```
I've implemented the second option in the last commit.
